[package]
name = "opencv_tracking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
dirs = "5.0.1"
opencv = "0.84.5"
tempfile = "3.8.0"
